# This playbook is for Amazon Linux
- hosts: susanoo
  become: yes
  become_user: root
  gather_facts: no
  vars:
    zone: Asia/Tokyo
    zoneinfo_path: /usr/share/zoneinfo/Asia/Tokyo

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
    - name: restart iptables
      service: name=iptables state=restarted
    - name: restart mysqld
      service: name=mysqld state=restarted

  tasks:
    - name: set zone to /etc/sysconfig/clock zone
      replace: >
        dest=/etc/sysconfig/clock
        regexp='^ZONE=\"UTC\"'
        replace='ZONE="{{zone}}"'
    - name: set zone to /etc/sysconfig/clock UTC
      lineinfile:
        dest: /etc/sysconfig/clock
        regexp:  '^UTC=.+$'
        line: 'UTC=false'
    - name: set localtime
      file: >
        src={{zoneinfo_path}}
        dest=/etc/localtime
        state=link
        force=yes

    - name: httpd.conf ServerName
      notify: restart httpd
      lineinfile:
        dest: /etc/httpd/conf/httpd.conf
        regexp: "^ServerName "
        line: "ServerName 127.0.0.1:80"
        insertafter: "^#ServerName .+:80"

    - name: httpd.conf NameVirtualHost
      notify: restart httpd
      lineinfile:
        dest: /etc/httpd/conf/httpd.conf
        regexp: "^NameVirtualHost "
        line: "NameVirtualHost *:80"
        insertafter: "^#NameVirtualHost"

    - name: find passenger config source
      command: '/usr/local/rbenv/shims/passenger-install-apache2-module --snippet'
      register: passenger_config
    - name: set passenger_config
      notify: restart httpd
      blockinfile:
        dest: /etc/httpd/conf.d/passenger.conf
        create: yes
        block: |
          {{passenger_config.stdout}}
        marker: "# {mark} ANSIBLE MANAGED BLOCK for passenger.conf"

    - name: httpd running
      service: name=httpd state=running enabled=yes

    - name: allow port http 80
      lineinfile:
        dest: /etc/sysconfig/iptables
        line: "-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT"
        insertafter: "^:OUTPUT "
      notify: restart iptables

    - name: mysql utf8 default
      ini_file:
        dest: /etc/my.cnf
        section: mysqld
        option: character-set-server
        value: utf8
      notify: restart mysqld